### ISSUE TITLE
Subscribe action form validation

### ISSUE THREAD

**Issue by theresao** [putyourlightson/craft-campaign#165] opened 2020-08-19 09:46 UTC
Does the actionSubscribe have a thorough validation of the form data before it is saved to the pendingcontacts database table?
E.g. will firstName and lastName strings be checked / is there a htmlspecialchars validation?

**Comment by bencroker** [comment] 2020-08-19 10:16
Sounds like a duplicate of https://github.com/putyourlightson/craft-campaign/issues/160?

**Comment by davidhellmann** [comment] 2020-08-25 09:06
@bencroker 
It looks like there is currently no Backend Form Validation there? 
Maybe it goes hand in hand with the #160 

Do you have a rough date for it?

**Comment by bencroker** [comment] 2020-08-25 09:39
It's a duplicate. Will look into addressing it today.

**Comment by bencroker** [comment] 2020-08-25 12:12
Added in version 1.15.6. See the mailing list subscribe form example for how to output errors:
https://putyourlightson.com/plugins/campaign#subscribe-form

**Closed as completed by bencroker** 2020-08-25 12:12 UTC
Labels: question
