### ISSUE TITLE
[v2] changing site menu on contact index page, throws a server error

### ISSUE THREAD

**Issue by vnali** [putyourlightson/craft-campaign#309] opened 2022-04-20 14:41 UTC
**Describe the bug**
on latest Campaign dev, when two site are enabled, changing site menu on contact index page, throws 'a server error occurred'

**Comment by bencroker** [comment] 2022-04-20 16:23
Thanks for reporting, I'm aware of this and awaiting the next Craft beta which resolves a similar issue before releasing a fix.
https://github.com/craftcms/cms/issues/10938

**Comment by vnali** [comment] 2022-04-22 12:45
@bencroker actually i report that issue and i am not sure if this issue is related to that issue.
some thoughts about the issue:
- i tested campaign on Craft 3 and it seems this issue still exists so i think this is not related to Craft 4.
- as far as i see, the contact email is not using isLocalized, so default value is set to false, but you tried to use localize it on another way.?
- you create a context menu manually for contact element in _layout.twig but it seems Craft context menu javascript is still applied so on changing site menu you can see a quick redirect and a server error, maybe because of aborted request
- i think [this issue](https://github.com/putyourlightson/craft-campaign/issues/310) is related to this fact that contact element isLocalized is set to false so creating contact on not primary site throws a invalid draft id

**Comment by bencroker** [comment] 2022-04-22 18:23
I'm not sure but I'll be reviewing all of this functionality once Craft 4.0.0-beta.5 is finally released.

**Comment by bencroker** [comment] 2022-04-23 18:27
Contacts, like users, are not localized, but the contact index page does have a site switcher, which determines which mailing lists and segments to show. I made some fixes in https://github.com/putyourlightson/craft-campaign/commit/2d7f66ed98994e0000837fc112d74fc8097956b6 but the error message continues to appear, even though the functionality is all working as expected, likely due to the aborted JS request, so I'll need to investigate further.

**Comment by bencroker** [comment] 2022-04-23 18:47
I can confirm that the error appears in recent versions of Craft 3 as well.

**Comment by bencroker** [comment] 2022-04-23 19:06
Fixed in https://github.com/putyourlightson/craft-campaign/commit/dd0800fe6e5f18027e50cfb3ce2a94cdb3aedc3c.

**Closed as completed by bencroker** 2022-04-23 19:06 UTC
Labels: bug
