### ISSUE TITLE
Searching a synced mailing list only shows contacts that are users

### ISSUE THREAD

**Issue by CustomCodeIT** [putyourlightson/craft-campaign#463] opened 2024-03-26 00:02 UTC
Please provide a clear and concise description of what the bug is, including:

### Reproduce

- Create a user group and add some users
- Use the Campaign sync feature to sync users from that group into a mailing list
- Manually add a contact to the mailing list
- Search for the manually added contact and note no search results.
- Interestingly, even after adding a manually created contact as a user, searching them still doesn't show results.

### Expectation
I expect to be able to search all contacts in a mailing list, whether they were synced from a user group or manually added.

### Screenshots

<img width="739" alt="image" src="https://github.com/putyourlightson/craft-campaign/assets/66106520/f4966b40-c2ce-4ad7-8ae2-cfba6d6242a5">

<img width="610" alt="image" src="https://github.com/putyourlightson/craft-campaign/assets/66106520/8d7a29d9-bb91-4678-8d83-eea257fa2854">

<img width="439" alt="image" src="https://github.com/putyourlightson/craft-campaign/assets/66106520/fa353ddf-1c37-4458-a1b5-0b066747bf95">

### Version Info

Craft Pro 4.8.5
Campaign Pro 2.13.0

### Other Notes

Tested on both an existing Craft site and a brand new fresh install.

**Comment by bencroker** [comment] 2024-03-26 01:15
I just tested manually adding a user locally. It was synced to a new contact and searching for the email address works just as expected. 

Does searching under “All contacts” work? Can you try it again with a new user, checking for any relevant errors in the logs?

**Comment by CustomCodeIT** [comment] 2024-03-26 01:24
That's correct and aligns with what I'm seeing. If you create a Craft user, everything works as expected. However, if you manually add a contact to a mailing list with sync enabled, that contact doesn't show in search results. Even if you create a Craft user matching that user email after the fact.

Searching under "All contacts" yields the same result. Logs all look clean with no errors or anything out of the norm

Edit: Updated my terminology in the original report as I said "user" where I should have said "contact"

**Comment by CustomCodeIT** [comment] 2024-03-26 01:42
If it helps demonstrate what I'm seeing:

https://www.youtube.com/watch?v=Ei6XZnUYK0w

**Comment by bencroker** [comment] 2024-03-26 02:17
Now that you clarified the issue is with creating a contact, I can replicate. It doesn’t look like the synced list plays any role in the issue, however. I’ll investigate and let you know what I find.

**Comment by CustomCodeIT** [comment] 2024-03-26 02:21
Yeah that's my bad, glad you're able to replicate it now though. Thanks for looking into it.

**Comment by bencroker** [comment] 2024-03-26 14:01
Fixed in https://github.com/putyourlightson/craft-campaign/commit/382062c22249fcbf8ae7c6e72f3bd9ca8d3522c6 for the next release.

**Closed as completed by bencroker** 2024-03-26 14:01 UTC
Labels: bug

**Comment by bencroker** [comment] 2024-03-26 14:11
Released in [2.13.1](https://github.com/putyourlightson/craft-campaign/releases/tag/2.13.1) and [3.0.0-beta.2](https://github.com/putyourlightson/craft-campaign/releases/tag/3.0.0-beta.2). Thanks for reporting this!
