### ISSUE TITLE
Mishandled error when trying to import a CSV of contacts without choosing a Mailing List

### ISSUE THREAD

**Issue by simple-nicholas** [putyourlightson/craft-campaign#144] opened 2020-05-21 02:02 UTC
### Describe the bug
When trying to import a CSV of contacts without choosing a Mailing List, a Type Error is thrown.

### To reproduce
Steps to reproduce the behaviour:

1. Go to /admin/campaign/contacts/import
2. Choose a csv file (doesn't seem to matter what's in it, so long as it's valid) and click "Next"
3. Choose Email and Full Name from the drop down, but not Mailing Lists

### Expected behaviour
Error message "Couldn't import file" should be displayed (the error shown appears to be an attempt to show this error), or prevent the form submission as a required field was not filled.

### Screenshots
![screen-shot](https://user-images.githubusercontent.com/50125070/82514817-d5d12380-9b55-11ea-9d47-ec9043f378ae.png)

### Versions
- Plugin version: 1.15.0 & 1.15.3
- Craft version: 3.4.16 & 3.4.20

**Comment by bencroker** [comment] 2020-05-21 07:33
Thanks, this is a duplicate of https://github.com/putyourlightson/craft-campaign/issues/141.

**Closed as completed by bencroker** 2020-05-21 07:33 UTC
Labels: bug
