### ISSUE TITLE
Sendout status not changed even if its progress is 100%

### ISSUE THREAD

**Issue by Saboteur777** [putyourlightson/craft-campaign#170] opened 2020-09-09 06:01 UTC
### Question
A sendout seems to be finished, as its progress reached 100%, but its status is "Queued". Is that intentional? _Fails_ count is 517, `maxSendFailsAllowed` is 500, I have just increased it to 1000.

**Comment by bencroker** [comment] 2020-09-09 10:55
What version of the plugin and Craft are you on? 517 failed attempts seems quite excessive, have you checked the `campaign.log` file to see if there are any clues as to what might be causing it to fail?

**Comment by Saboteur777** [comment] 2020-09-09 11:33
It is below 10%, but it is quite high, yes. (This is an imported userbase, with no e-mail validation on the old site, so I expected this.)

I did: I have found some invalid addresses there, but a lot of valid e-mail, like r************@gmail.com (redacted for privacy reasons, but first segment looked fine, too). 

edit: I checked the failing e-mail addresses, some of them contained typos, fixed them. I removed all non-existent e-mail addresses (checked with an e-mail validator service), but the sendout is still _Queued_. 

Plugin version: 1.15.6
Craft: 3.5.8

**Comment by bencroker** [comment] 2020-09-09 11:49
Good to hear you cleaned up the list. Failed attempts at valid email addresses are most likely being caused by your email service provider rejecting them.

To run the queue jobs, run this command:
`./craft queue/run`

**Comment by Saboteur777** [comment] 2020-09-09 12:10
Queue is run every minute and I don't see any stuck jobs. Running `craft campaign/sendouts/run-pending-sendouts` responds with `0 pending sendout(s) queued.`, but the sendout is still stuck on Queued status. 

![kepernyokep_20200909_140327](https://user-images.githubusercontent.com/9061795/92596470-25269580-f2a6-11ea-8adb-429a69a2b39b.jpg)

**Comment by bencroker** [comment] 2020-09-09 12:15
Can you pause the sendout and then restart it?

**Comment by Saboteur777** [comment] 2020-09-09 12:22
That did the trick, thanks!

**Comment by Saboteur777** [comment] 2020-10-14 14:53
Sorry for reopening this: the issue is still here. 
If the sendout experiences fails, then the sendout is getting executed repeatedly via a cronjob, thus inflating the fail count and never succeed. 

In details: the sendout is almost complete (it is at 100%), but there were fails during the sending process. A recent example: the sendout has 1765 recipient, fail count is 4, expected recipients is 4 after the first tick. When the cronjob triggers the sendout, it is queued up again, finishes fast and the fail count is now 8, the recipients count is still 4. And this happens again and again, until the sendout is cancelled.

**Comment by bencroker** [comment] 2020-10-14 15:52
Ok thanks, I'll look into whether this might be a bug.

**Comment by Saboteur777** [comment] 2020-10-20 16:30
Thanks! Let me know if you need anything for this from me.

**Comment by bencroker** [comment] 2020-11-03 23:14
Fixed in https://github.com/putyourlightson/craft-campaign/commit/375f5066b807c2c59ef5219388f43d7b91d6e2fa for the next release.

**Closed as completed by bencroker** 2020-11-03 23:14 UTC
Labels: bug

**Comment by bencroker** [comment] 2020-11-05 20:08
Released in 1.17.0.

**Comment by Saboteur777** [comment] 2020-11-23 17:36
Thank you Ben - we evaluated this in the last weeks and it is definitely solved! :partying_face:

**Comment by bencroker** [comment] 2020-11-23 17:51
Glad to hear it!
