### ISSUE TITLE
Verification link error - impossible to join mailing list from website

### ISSUE THREAD

**Issue by iparr** [putyourlightson/craft-campaign#338] opened 2022-10-27 13:24 UTC
_(Two bug reports in one day, sorry but it's just a bad day!)_

When users sign-up from an on-website form they are sent an email (this is the default one, I've not changed the template).

This includes a link and upon following that link they get an error.

This is:
`Typed property putyourlightson\campaign\models\PendingContactModel::$mailingListId must not be accessed before initialization`

This has been working fine as far as I'm aware and has just started the problem with version 2.1.14 (plus Craft 4.3.0). I am using PHP 8.1.

It was reported by a visitor, but I've been able to reproduce exactly the same error upon signing up myself.

Line 189 in  in `/vendor/putyourlightson/craft-campaign/src/controllers/FormsController.php`:
`$mailingList = Campaign::$plugin->mailingLists->getMailingListById($pendingContact->mailingListId);`

**Comment by bencroker** [comment] 2022-10-27 14:50
This is caused by a [breaking change](https://github.com/yiisoft/yii2/issues/19546#issuecomment-1291280606https://github.com/yiisoft/yii2/issues/19546#issuecomment-1291280606) in Yii 2.0.46 and was fixed in Campaign 2.1.14, however it appears one property was missed! Fixed in https://github.com/putyourlightson/craft-campaign/commit/1b7240ad33c15b02a5ab090b98e4ac807ef054c5 and released in 2.1.15.

**Closed as completed by bencroker** 2022-10-27 14:50 UTC
Labels: bug

**Comment by iparr** [comment] 2022-10-27 16:15
Can confirm that this fixes my scenario. Cheers.
