### ISSUE TITLE
Regular exceptions - `Trying to get property 'email' of non-object`

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-campaign#149] opened 2020-06-15 06:05 UTC
### Describe the bug

In our Rollbar logs, I am seeing, on a regular basis, an exception:

`Trying to get property 'email' of non-object`

The urls being hit look like:

`https://oursite.com.au/actions/campaign/forms/verify-subscribe?pid=p5ee5d2051b22bj3l`

Sometimes I see more than one of these errors in the logs.

If I look in the pending contacts table, I _don't_ see a `pid` with the values.

So my guess is that maybe they are hitting the verify url more than once (e.g. restarting a browser where that url was open in a tab or whatever) - and because they've already verified, there's no record to be found any more?

I guess I am just checking if I need to worry about these (if not, I can mute them, for example).  

I wonder if there is a more elegant way of handling this issue (if this is indeed the issue).

### Versions
- Plugin version: Latest stable
- Craft version: 3.4.23

**Comment by bencroker** [comment] 2020-06-15 15:25
Fixed in https://github.com/putyourlightson/craft-campaign/commit/3d5c702e739495f4b3a4028045613235a34208d2, thanks!

**Comment by joergennoraas** [comment] 2020-06-22 07:06
@bencroker We had the same bug and updated to 1.15.4 today. We think the problem is connected to Microsofts safelink protection in outlook, and that they somehow do a get on the verification link before the user loads the page. After we updated we get the error "Verification link has expired" probably thrown here https://github.com/putyourlightson/craft-campaign/blob/85f0340a3688a79610e0f9898f1d5e40ea084796/src/controllers/FormsController.php#L283 I can see that the subscription is verified, but the user gets an error.  Should I create a new bug?

**Comment by bencroker** [comment] 2020-06-22 08:29
Once a pending contact verifies their email, the verification link expires and the exception message correctly reflects that. What kind of behaviour would you expect in this scenario?

**Comment by joergennoraas** [comment] 2020-06-22 08:55
I know. The problem is that the user doesn't see that the url is getting called. So the user only gets a 404 page saying "Verification link has expired". Since this seems to be the Microsoft safelink thing, I would guess that quite a few users are experiencing this error. If you would like, we could do a screen sharing session and I could show you what is happening.

**Comment by bencroker** [comment] 2020-06-22 08:57
That's ok, I think I understand, I'm just wondering what the plugin should do about this as it is not a bug per se. I suppose the verification link could expire only the second time it is accessed but that seems a bit unusual.

**Comment by joergennoraas** [comment] 2020-06-22 09:02
If it is possible to check if the link has been verified before and give another message it would be better. But I don't have a good solution in mind. I only know this is a problem.

**Comment by bencroker** [comment] 2020-06-22 09:04
That would require keeping expired verification links around for an extended period of time, which sounds rather unappealing. I'll keep this issue open and see what I come up with.

**Comment by bossanova808** [comment] 2020-06-23 00:10
Perhaps keep them for ~a month, and mark in the DB which have been used or not.  Used ones could, for that month, result in 'you've already verified' message (maybe only _after_ the 2nd hit, given the Outlooks scenario above.  After some duration, I don't think anyone could reasonably expect anything other than an error, but the key issue is that first few days when they sometimes seem to hit the link multiple times.

Just food for thought!

**Comment by bencroker** [comment] 2020-06-24 09:00
This must affect other aspects of Craft such as activating accounts. What kind of behaviour have you seen in such situations?

**Comment by bossanova808** [comment] 2020-06-24 09:18
In our case, because 90% of our customers are registering during a checkout, I don't actually use activation emails as such (they get an email about setting their password, but I haven't seen any exception scenarios with those).

**Comment by bencroker** [comment] 2020-06-24 10:22
What about for you @joergennoraas?

**Comment by joergennoraas** [comment] 2020-06-24 10:30
We run a public Norwegian department web site, It is only employees that have accounts in craft, the process of creating craft users is therefore more manual and we haven't seen this issue there.

**Comment by bossanova808** [comment] 2020-07-29 03:54
Just a note - don't seem to be seeing these anymore.  I'm fine with you closing this one...

**Closed as completed** 2020-07-29 16:47 UTC
Labels: bug
