### ISSUE TITLE
Bad Gateway Error when viewing completed Sendouts in Craft CMS 4.0.4 and later

### ISSUE THREAD

**Issue by cquinders** [putyourlightson/craft-campaign#316] opened 2022-06-23 13:54 UTC
After the Update to Craft CMS 4.0.4 I can no longer view completed Sendouts in the CP. Clicking on any completed (or send) Sendout from the Sendouts element index page gives me a 502 Bad Gateway error.

Updating Craft CMS to the latest Version 4.0.5.1 doesn’t solve the issue, but after downgrading to Craft CMS 4.0.3 completed Sendouts can be viewed again.

- Craft CMS 4.0.4+
- Craft Campaign Pro 2.0.3

**Comment by bencroker** [comment] 2022-06-23 21:47
Thanks for reporting!! I can confirm that this is indeed an issue since Craft 4.0.4 and will look it.

**Comment by bencroker** [comment] 2022-06-24 08:35
Fixed in https://github.com/putyourlightson/craft-campaign/commit/a0e23891cacfa0e7709dbfb8c0bdee6693b42523 and released in version 2.0.4.

**Closed as completed by bencroker** 2022-06-24 08:35 UTC
Labels: bug
