### ISSUE TITLE
Issue with entry field in Contact 

### ISSUE THREAD

**Issue by scandella** [putyourlightson/craft-campaign#414] opened 2023-09-17 10:37 UTC
Sorry, this won't be a very clear report…
I have a strange issue when using an entry field in a Contact layout.
When I add a new contact, I can populate the entry field and then save these field entries with the Contact.
But then, when I reopen the Contact or any previously saved contact,  I can add or remove entries to this Entry field but the changes are not saved although no error is raised! All other changes to the other fields are correctly saved.
Using the very same entry field in any section works fine.
No Js error appears, and I can't find a trace of this behavior in the Logs. 
I haven't had a chance to try to reproduce it in a fresh install yet but I would like to know if you can give me a clue where to look for.
[Here a small demo of the issue.](https://navette.scandella.fr/lcueogia)

Best,

**Comment by bencroker** [comment] 2023-09-18 05:55
I can confirm this is indeed happening with Campaign 2.8.5 and Craft 4.5.5 and will work on a fix this week.

**Comment by rebkuhn** [comment] 2023-09-19 14:05
Hi. I assume we are experiencing the same problem with the category fields: since we updated Craft to 4.5.5 and the Campaign to 2.8.5, we can no longer save the category fields on the contact entries. It is still possible to select and remove categories, but the changes are not saved.
Best regards

**Comment by bencroker** [comment] 2023-09-19 20:34
Yup, sounds like the same issue. Am still working on getting this resolved.

**Comment by rebkuhn** [comment] 2023-09-25 08:40
Hi Ben. I would like to ask whether you have made any progress in solving the problem with the category fields on the contacts. I’m asking, because our customer wants to do a campaign sendout on friday this week and needs to change/add some categories on some contacts before that. Do you think the fix will be available by then?

**Comment by bencroker** [comment] 2023-09-25 08:43
I can’t promise, but will prioritise it.

**Comment by rebkuhn** [comment] 2023-09-25 13:04
> I can’t promise, but will prioritise it.

Thank you!

**Comment by bencroker** [comment] 2023-09-25 18:36
Something seems to have changed in Craft 4.5.4. This should be fixed in https://github.com/putyourlightson/craft-campaign/commit/f78c9991aba1d918117eef04c4eb33559a63ddc3. Released in version 2.8.7.

**Closed as completed by bencroker** 2023-09-25 18:36 UTC
Labels: bug

**Comment by scandella** [comment] 2023-09-25 18:45
👍
